### ISSUE TITLE
Note that you'd need to run a web-server to use this.

### ISSUE THREAD

**Issue by ghost** [captn3m0/codechef#1]
when I open the problems I get html code but not the problem how can I get the problems?

**Comment by captn3m0** [comment]
This is hosted at https://captnemo.in/codechef/

strip.php might be able to regenerate the data, but you'll need to pass it a list of problems by editing the lists directory, I think.

This was hacked together a long time back, and is not really supported. If you'd like to work on it, I'll add you to the collaborators :+1: 

The web-server requirement is because browsers don't allow ajax requests in file:///

**Comment by ghost** [comment]
Can you please send that list if possible?

**Comment by captn3m0** [comment]
Its already part of the repo. See `list` directory.

**Comment by gaddevarunteja** [comment]
What should I change in it?
should I add spaces in between?

**Comment by ghost** [comment]
Should we pass arguments in command line?

**Comment by captn3m0** [comment]
You need to run wget -i over the problem lists (EASY.txt etc). Then run strip.php with the directory as the argument.

For this to work, you need to update EASY.txt first, though. For that, I believe I just ran jQuery on the codechef easy listings webpage.
